QUERY_FINANCEIRO = '''
SELECT
	C.NOMEINTERNO AS 'CLIENTE',
	P.Pasta,
	CASE WHEN P.STATUS = 1 THEN 'ATIVO' ELSE 'ENCERRADO' END AS 'STATUS PASTA',
	P.NumProcessoCNJ,
	P.ControleCliente,
	TN.DESCNUCLEO AS 'NUCLEO',
	TP.TipoProcesso AS 'TIPO AÇÃO',
    TIPOSEGMENTO.TIPOSEGMENTO AS 'TIPO_SEGMENTO',
	CO.NomeComarca AS 'COMARCA',
	CO.UF,
	PA.AUTOR,
	PA.CPF_CNPJ_AUTOR,
	PA.REU,
	PA.CPF_CNPJ_REU,
	RC.Responsavel AS 'AGENCIA/RESPONSAVEL',
	JURIS.DescJurisdicao AS 'COMPETENCIA',
	CAST(P.DTAJUIZAMENTO AS DATE) AS 'DTAJUIZAMENTO/DTDISTRIBUICAO'

FROM TOTAL_FC.DBO.TBPROCESSOS AS P
	LEFT JOIN TOTAL_FC.DBO.tbClientes AS C ON C.IDCLIENTE = P.IDCLIENTE
	LEFT JOIN TOTAL_FC.DBO.tbTipoNucleo AS TN ON TN.Id = P.IdNucleo
	LEFT JOIN TOTAL_FC.DBO.TBADVOGADOS AS ADV ON ADV.CODADVOGADO = P.CODADVOGADO
	LEFT JOIN TOTAL_FC.DBO.tbTipoProcesso AS TP ON TP.IdTipoProcesso = P.IdTipoProcesso
	LEFT JOIN TOTAL_FC.DBO.tbComarcas AS CO ON CO.IdComarca = P.IdComarca
	LEFT JOIN TOTAL_FC.DBO.TbResponsavelCliente AS RC ON RC.IdResponsavelCliente = P.IdResponsavelCliente
	LEFT JOIN TOTAL_FC.DBO.TbJurisdicao AS JURIS ON JURIS.CodJurisdicao = P.CodJurisdicao
    LEFT JOIN TOTAL_FC.DBO.TBTIPOSEGMENTO AS TIPOSEGMENTO ON P.CODTIPOSEGMENTO = TIPOSEGMENTO.ID


	OUTER APPLY(
		SELECT 
			MIS.DBO.REMOVE_QUEBRA_LINHA(PA.NOMEPARTE) AS 'AUTOR'
			,PP.CLIENTE AS AUTOR_CLIENTE
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PC.DESCPARTECONTRARIA) AS 'ADV_PARTE_AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(PA.DOC) AS 'CPF_CNPJ_AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PA1.NOMEPARTE) AS 'REU'
			,PP1.CLIENTE AS REU_CLIENTE
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PC1.DESCPARTECONTRARIA) AS 'ADV_PARTE_REU'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(PA1.DOC) AS 'CPF_CNPJ_REU'
		
		FROM 
			TOTAL_FC.DBO.TBPROCESSOS AS P1
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP  ON P1.IDPROC = PP.IDPROC AND (PP.STATUS = 'AUTOR')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA  ON PA.IDPARTE = PP.IDPARTE
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP1  ON P1.IDPROC = PP1.IDPROC AND (PP1.STATUS = 'REU')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA1  ON PA1.IDPARTE = PP1.IDPARTE
			LEFT JOIN TOTAL_FC.DBO.TBPARTECONTRARIA AS PC ON PP.CODPARTECONTRARIA = PC.CODPARTECONTRARIA
			LEFT JOIN TOTAL_FC.DBO.TBPARTECONTRARIA AS PC1 ON PP1.CODPARTECONTRARIA = PC1.CODPARTECONTRARIA
		WHERE P1.IDPROC = P.IDPROC

	) AS PA

WHERE P.IDCLIENTE = {id_cliente}
'''

QUERY_FINANCEIRO_BNB = '''
SELECT
	C.NOMEINTERNO AS 'CLIENTE',
	P.Pasta,
	CASE WHEN P.STATUS = 1 THEN 'ATIVO' ELSE 'ENCERRADO' END AS 'STATUS PASTA',
	P.NumProcessoCNJ,
	P.ControleCliente,
	TN.DESCNUCLEO AS 'NUCLEO',
	TP.TipoProcesso AS 'TIPO AÇÃO',
    TIPOSEGMENTO.TIPOSEGMENTO AS 'TIPO_SEGMENTO',
	CO.NomeComarca AS 'COMARCA',
	CO.UF,
	PA.AUTOR,
	PA.CPF_CNPJ_AUTOR,
	PA.REU,
	PA.CPF_CNPJ_REU,
	RC.Responsavel AS 'AGENCIA/RESPONSAVEL',
	JURIS.DescJurisdicao AS 'COMPETENCIA',
	CAST(P.DTAJUIZAMENTO AS DATE) AS 'DTAJUIZAMENTO/DTDISTRIBUICAO'

FROM TOTAL_FC.DBO.TBPROCESSOS AS P
	LEFT JOIN TOTAL_FC.DBO.tbClientes AS C ON C.IDCLIENTE = P.IDCLIENTE
	LEFT JOIN TOTAL_FC.DBO.tbTipoNucleo AS TN ON TN.Id = P.IdNucleo
	LEFT JOIN TOTAL_FC.DBO.TBADVOGADOS AS ADV ON ADV.CODADVOGADO = P.CODADVOGADO
	LEFT JOIN TOTAL_FC.DBO.tbTipoProcesso AS TP ON TP.IdTipoProcesso = P.IdTipoProcesso
	LEFT JOIN TOTAL_FC.DBO.tbComarcas AS CO ON CO.IdComarca = P.IdComarca
	LEFT JOIN TOTAL_FC.DBO.TbResponsavelCliente AS RC ON RC.IdResponsavelCliente = P.IdResponsavelCliente
	LEFT JOIN TOTAL_FC.DBO.TbJurisdicao AS JURIS ON JURIS.CodJurisdicao = P.CodJurisdicao
    LEFT JOIN TOTAL_FC.DBO.TBTIPOSEGMENTO AS TIPOSEGMENTO ON P.CODTIPOSEGMENTO = TIPOSEGMENTO.ID


	OUTER APPLY(
		SELECT 
			MIS.DBO.REMOVE_QUEBRA_LINHA(PA.NOMEPARTE) AS 'AUTOR'
			,PP.CLIENTE AS AUTOR_CLIENTE
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PC.DESCPARTECONTRARIA) AS 'ADV_PARTE_AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(PA.DOC) AS 'CPF_CNPJ_AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PA1.NOMEPARTE) AS 'REU'
			,PP1.CLIENTE AS REU_CLIENTE
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PC1.DESCPARTECONTRARIA) AS 'ADV_PARTE_REU'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(PA1.DOC) AS 'CPF_CNPJ_REU'
		
		FROM 
			TOTAL_FC.DBO.TBPROCESSOS AS P1
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP  ON P1.IDPROC = PP.IDPROC AND (PP.STATUS = 'AUTOR')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA  ON PA.IDPARTE = PP.IDPARTE
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP1  ON P1.IDPROC = PP1.IDPROC AND (PP1.STATUS = 'REU')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA1  ON PA1.IDPARTE = PP1.IDPARTE
			LEFT JOIN TOTAL_FC.DBO.TBPARTECONTRARIA AS PC ON PP.CODPARTECONTRARIA = PC.CODPARTECONTRARIA
			LEFT JOIN TOTAL_FC.DBO.TBPARTECONTRARIA AS PC1 ON PP1.CODPARTECONTRARIA = PC1.CODPARTECONTRARIA
		WHERE P1.IDPROC = P.IDPROC

	) AS PA

WHERE P.IDCLIENTE IN (602, 603, 594, 604, 605, 606)
'''

QUERY_BATIMENTO = '''
SELECT
	 PROCESSOS.PASTA
	,CASE 
		 WHEN PROCESSOS.STATUS = 1 THEN 'ATIVO' 
		 WHEN PROCESSOS.STATUS = 5 THEN 'ENCERRADO' 
		 ELSE CAST(PROCESSOS.STATUS AS VARCHAR) 
	 END AS 'STATUS'
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.NUMPROCESSOCNJ) AS 'NUMPROCESSOCNJ'
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.CONTROLECLIENTE) AS 'CONTROLECLIENTE'
	,CLIENTES.NOMEINTERNO AS 'CLIENTE'
	,TIPONUCLEO.DESCNUCLEO AS 'NÚCLEO'
	,ADVOGADOS.NOMEADVOGADO AS ADVOGADO_RESPONSÁVEL
	,CASE 
		 WHEN PROCESSOS.PROCELETRONICO = 'NAO' THEN 'FÍSICO' 
		 WHEN PROCESSOS.PROCELETRONICO = 'SIM' THEN 'ELETRÔNICO' 
		 ELSE CAST(PROCESSOS.PROCELETRONICO AS VARCHAR) 
	 END AS 'TIPO_PROCESSO'
	,PROCESSOS.USERCADASTRO AS USER_CADASTRO_PASTA
	,CAST(PROCESSOS.DTCADASTRO AS DATE) AS 'DT_CADASTRO'
	,CAST(DTAJUIZAMENTO AS DATE)  AS 'DT_DISTRIBUICAO'
	,CAST(DTTERCEIRIZACAO AS DATE)  AS 'DT_TERCEIRIZAÇÃO'
	,FASESPROC.DESCFASEPROC AS FASE
	,PROCESSOS.VLRCAUSA AS VALOR
	,TIPOPROCESSO.TIPOPROCESSO AS 'TIPO_AÇÃO'
	,COMARCAS.NOMECOMARCA AS 'COMARCA'
	,COMARCAS.UF
	,MIS.DBO.REMOVE_QUEBRA_LINHA(CORRESPONDENTES.NOMECORRESPONDENTE) AS 'CORRESPONDENTE'
	,PROCESSOS.VARA AS 'VARA'
	,JURISDICAO.DESCJURISDICAO AS 'COMPETÊNCIA'
	,MIS.DBO.REMOVE_QUEBRA_LINHA(TIPOSEGMENTO.TIPOSEGMENTO) AS 'TIPO_SEGMENTO'
	,CLASSIFICACAO.DESCCLASSIFICAÇÃO AS 'CLASSIFICAÇÃO'
	,PA.AUTOR
	,PA.[CPF_CNPJ_AUTOR]
	,PA.RÉU
	,PA.[CPF_CNPJ_RÉU]
	,AP.[DESCRIÇÃO ANDAMENTO_PROCESSUAL] AS 'ÚLTIMO ANDAMENTO_PROCESSUAL'
	,AP.[DT ANDAMENTO_PROCESSUAL] AS 'DT ANDAMENTO_PROCESSUAL'
	,AP.TEXTO_ANDAMENTO_PROCESSUAL
	,AP.ANDAMENTO_PROCESSUAL_INCLUIDO_POR
	,AP2.[DESCRIÇÃO ANDAMENTO_INTERNO]
	,AP2.[DT ANDAMENTO_INTERNO]
	,AP2.TEXTO_ANDAMENTO_INTERNO
	,AP2.ANDAMENTO_INTERNO_INCLUIDO_POR
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.RESUMOPROCESSO) AS 'OBJETO'
	,PRODUTOS.DESCPRODUTO AS 'PRODUTO'
	,MATERIA.DESCMATERIA AS MATERIA
	,PROCESSOS.RITO
	,CASE WHEN PROCESSOS.COBRAVEL = 1 THEN 'SIM' ELSE 'NÃO' END AS 'NÃO COBRÁVEL'
	,PROCESSOS.ESTRATEGICO
	,CAST(PROCESSOS.DTENCERRAMENTO AS DATE) AS 'DT_ENCERRAMENTO' 
	,ENCERRAMENTOS.DESCENCERRAMENTO
	,MIS.DBO.REMOVE_QUEBRA_LINHA(MOTIVOESTRATEGICO.DESCRICAO) AS MOTIVO_ESTRATÉGICO
	,CASE 
		 WHEN PROCESSOS.TIPOPROCSUSPENSO = 'PROPSUSP' THEN 'PROPENSOS A SUSPENSÃO'
		 WHEN PROCESSOS.TIPOPROCSUSPENSO = 'SUSPDECSTF' THEN 'SUSPENSOS - DECISÃO STF'
		 ELSE 'NENHUM' 
	 END AS 'TIPO_SUSPENSÃO'
	,CAST(PROCESSOS.DTTIPOPROCSUSPENSO AS DATE) AS 'DT_SUSPENSÃO'
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.OBS) AS 'OBS'
	,FLUXOS.DESCFLUXO AS 'FLUXO MAX'
	,ETAPAS.DESCETAPA AS 'ETAPA DO ADVOGADO' 
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.NUMPROCESSO2) AS NUMPROC2
	,MIS.DBO.REMOVE_QUEBRA_LINHA(PROCESSOS.NUMPROCESSONOVO) AS NUMPROCNOVO
	,PROCEDIMENTOS.NomeProcedimento AS 'NOMEPROCEDIMENTO'
FROM
	TOTAL_FC.DBO.TBPROCESSOS AS PROCESSOS
	INNER JOIN MIS.RPA.BASEBATIMENTOCADASTRAMENTOBB AS BASE {ligacao_select}
	LEFT JOIN TOTAL_FC.DBO.TBTIPOPROCESSO AS TIPOPROCESSO  ON TIPOPROCESSO.IDTIPOPROCESSO = PROCESSOS.IDTIPOPROCESSO
	LEFT JOIN TOTAL_FC.DBO.TBCLIENTES AS CLIENTES ON PROCESSOS.IDCLIENTE = CLIENTES.IDCLIENTE
	LEFT JOIN TOTAL_FC.DBO.TBCOMARCAS AS COMARCAS ON PROCESSOS.IDCOMARCA = COMARCAS.IDCOMARCA
	LEFT JOIN TOTAL_FC.DBO.TBJURISDICAO AS JURISDICAO ON PROCESSOS.CODJURISDICAO	= JURISDICAO.CODJURISDICAO
	LEFT JOIN TOTAL_FC.DBO.TBADVOGADOS AS ADVOGADOS ON PROCESSOS.CODADVOGADO = ADVOGADOS.CODADVOGADO
	LEFT JOIN TOTAL_FC.DBO.TBCLASSIFICACAO AS CLASSIFICACAO ON PROCESSOS.CODCLASSIFICACAO = CLASSIFICACAO.CODCLASSIFICACAO
	LEFT JOIN TOTAL_FC.DBO.TBTIPOSEGMENTO AS TIPOSEGMENTO ON PROCESSOS.CODTIPOSEGMENTO = TIPOSEGMENTO.ID
	LEFT JOIN TOTAL_FC.DBO.TBTIPONUCLEO AS TIPONUCLEO ON PROCESSOS.IDNUCLEO = TIPONUCLEO.ID
	LEFT JOIN TOTAL_FC.DBO.TBFASESPROC AS FASESPROC ON PROCESSOS.CODFASE = FASESPROC.CODFASEPROC
	LEFT JOIN TOTAL_FC.DBO.TBCORRESPONDENTES AS CORRESPONDENTES ON PROCESSOS.CODCORRESPONDENTE = CORRESPONDENTES.CODCORRESPONDENTE
	LEFT JOIN TOTAL_FC.DBO.TBPRODUTOS AS PRODUTOS ON PROCESSOS.IDPRODUTO = PRODUTOS.IDPRODUTO
	LEFT JOIN TOTAL_FC.DBO.TBMOTIVOESTRATEGICO AS MOTIVOESTRATEGICO ON PROCESSOS.IDMOTESTRATEGICO = MOTIVOESTRATEGICO.ID
	LEFT JOIN TOTAL_FC.DBO.TBTIPOCITACAO AS TIPOCITACAO ON PROCESSOS.CODCITACAO = TIPOCITACAO.CODCITACAO
	LEFT JOIN TOTAL_FC.DBO.TBTIPOPENHORA AS TIPOPENHORA ON PROCESSOS.CODPENHORA = TIPOPENHORA.CODPENHORA 
	LEFT JOIN TOTAL_FC.DBO.TBRATINGPROCESSO AS RATINGPROCESSO ON PROCESSOS.CODRATING =  RATINGPROCESSO.ID
	LEFT JOIN TOTAL_FC.DBO.TBENCERRAMENTOS AS ENCERRAMENTOS ON ENCERRAMENTOS.CODENCERRAMENTO = PROCESSOS.CODENCERRAMENTO
	LEFT JOIN TOTAL_FC.DBO.TBFLUXOPROCESSOS AS FLUXOPROCESSO ON FLUXOPROCESSO.CODFLUXOPROCESSO = PROCESSOS.CODFLUXOPROCESSOATUAL
	LEFT JOIN TOTAL_FC.DBO.TBFLUXOS AS FLUXOS ON FLUXOS.CODFLUXO = FLUXOPROCESSO.CODFLUXO
	LEFT JOIN TOTAL_FC.DBO.TBETAPASFLUXO AS ETAPASFLUXOS ON ETAPASFLUXOS.CODETAPAFLUXO = FLUXOPROCESSO.CODETAPAFLUXO
	LEFT JOIN TOTAL_FC.DBO.TBETAPAS AS ETAPAS ON ETAPAS.CODETAPA = ETAPASFLUXOS.CODETAPA
	LEFT JOIN TOTAL_FC.DBO.TBMATERIAS AS MATERIA ON MATERIA.CODMATERIA = PROCESSOS.CODMATERIA
	LEFT JOIN TOTAL_FC.DBO.tbProcedimentos AS PROCEDIMENTOS ON PROCEDIMENTOS.IdProcedimento = PROCESSOS.IdProcedimento
	

	OUTER APPLY(
		SELECT TOP 1
			 MIS.DBO.REMOVE_QUEBRA_LINHA(PA.NOMEPARTE) AS 'AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PA.DOC) AS 'CPF_CNPJ_AUTOR'
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PA1.NOMEPARTE) AS 'RÉU'
			,MIS.DBO.REMOVE_QUEBRA_LINHA(PA1.DOC) AS 'CPF_CNPJ_RÉU'
		FROM 
			TOTAL_FC.DBO.TBPROCESSOS AS P1
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP  ON P1.IDPROC = PP.IDPROC AND (PP.STATUS = 'AUTOR')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA  ON PA.IDPARTE = PP.IDPARTE
			LEFT JOIN TOTAL_FC.DBO.TBPARTESPROCESSOS AS PP1  ON P1.IDPROC = PP1.IDPROC AND (PP1.STATUS = 'REU')
			LEFT JOIN TOTAL_FC.DBO.TBPARTES AS PA1  ON PA1.IDPARTE = PP1.IDPARTE
		WHERE P1.IDPROC = PROCESSOS.IDPROC 
		ORDER BY PA.DTINCLUSAO DESC
	) AS PA

	OUTER APPLY(
		SELECT TOP 1
			 MIS.DBO.REMOVE_QUEBRA_LINHA_2(RA.DESCRICAO) AS 'DESCRIÇÃO ANDAMENTO_PROCESSUAL'
			,CONVERT(VARCHAR(10),ANDAMPROCESSUAL.DATA,103) AS 'DT ANDAMENTO_PROCESSUAL'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(ANDAMPROCESSUAL.TEXTO) AS 'TEXTO_ANDAMENTO_PROCESSUAL'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(ANDAMPROCESSUAL.USERCADASTRA) AS 'ANDAMENTO_PROCESSUAL_INCLUIDO_POR'
		FROM 
			TOTAL_FC.DBO.TBANDAMPROCESSUAL AS ANDAMPROCESSUAL		
			LEFT JOIN TOTAL_FC.DBO.TBRESUMOSANDAMENTOS AS RA ON ANDAMPROCESSUAL.CODANDAMENTO = RA.CODRESUMO	
		WHERE
			PROCESSOS.IDPROC = ANDAMPROCESSUAL.IDPROC 
			AND ANDAMPROCESSUAL.STATUS = 'VÁLIDO' 
			AND RA.CLASSIFICACAO = 'PROCESSUAL'
			AND ANDAMPROCESSUAL.DATA <> '1980-01-01'
		ORDER BY ANDAMPROCESSUAL.DATA DESC
	) AS AP
	
	OUTER APPLY(
		SELECT TOP 1
			 MIS.DBO.REMOVE_QUEBRA_LINHA_2(RA.DESCRICAO) AS 'DESCRIÇÃO ANDAMENTO_INTERNO'
			,CONVERT(VARCHAR(10),ANDAMPROCESSUAL.DATA,103) AS 'DT ANDAMENTO_INTERNO'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(ANDAMPROCESSUAL.TEXTO) AS 'TEXTO_ANDAMENTO_INTERNO'
			,MIS.DBO.REMOVE_QUEBRA_LINHA_2(ANDAMPROCESSUAL.USERCADASTRA) AS 'ANDAMENTO_INTERNO_INCLUIDO_POR'
		FROM 
			TOTAL_FC.DBO.TBANDAMPROCESSUAL AS ANDAMPROCESSUAL
			LEFT JOIN TOTAL_FC.DBO.TBRESUMOSANDAMENTOS AS RA ON ANDAMPROCESSUAL.CODANDAMENTO = RA.CODRESUMO
		WHERE
			PROCESSOS.IDPROC = ANDAMPROCESSUAL.IDPROC 
			AND ANDAMPROCESSUAL.STATUS = 'VÁLIDO'
			AND RA.CLASSIFICACAO = 'INTERNO'
			AND ANDAMPROCESSUAL.DATA <> '1980-01-01'
		ORDER BY ANDAMPROCESSUAL.DATA DESC
	) AS AP2

	WHERE PROCESSOS.IDCLIENTE IN ({lista_id_clientes})
    '''

DICIO_SELECT_QUERY = {
    'controlecliente': 'ON BASE.CONTROLECLIENTE COLLATE SQL_Latin1_General_CP850_CI_AI = PROCESSOS.CONTROLECLIENTE', 
    'numprocessocnj': 'ON BASE.NUMPROCESSOCNJ COLLATE SQL_Latin1_General_CP850_CI_AI = PROCESSOS.NUMPROCESSOCNJ', 
    'pasta': 'ON BASE.PASTA = PROCESSOS.PASTA',
}